# Generated by Django 4.2.6 on 2023-10-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(verbose_name='Data'),
        ),
    ]
